FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN mkdir /code \
	&& echo \
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free \
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free \
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free \
deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free \
> /etc/apt/sources.list \
	&& apt-get update

WORKDIR /code

COPY . /code/

RUN pip install pip -U -i https://pypi.tuna.tsinghua.edu.cn/simple \
	&& pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

