# Generated by Django 2.2.6 on 2019-10-12 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191012_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 10, 1, 55, 685395, tzinfo=utc)),
        ),
    ]
