# Generated by Django 2.2.6 on 2019-10-13 03:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20191013_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='update',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 3, 7, 7, 382397, tzinfo=utc)),
        ),
    ]
