# Generated by Django 2.2.6 on 2019-10-13 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20191013_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(upload_to='article/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 6, 16, 57, 933618, tzinfo=utc)),
        ),
    ]
