# Generated by Django 2.2.6 on 2019-10-13 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20191013_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 12, 49, 46, 438011, tzinfo=utc)),
        ),
    ]
