# Generated by Django 2.2.6 on 2019-10-14 04:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20191014_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 4, 54, 40, 732438, tzinfo=utc)),
        ),
    ]
