# Generated by Django 2.2.6 on 2019-10-21 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20191021_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 5, 38, 9, 615045, tzinfo=utc)),
        ),
    ]
