# Generated by Django 2.2.6 on 2019-10-21 06:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20191021_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 6, 4, 4, 793273, tzinfo=utc)),
        ),
    ]
