# Generated by Django 2.2.6 on 2019-10-22 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20191021_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 6, 2, 34, 447276, tzinfo=utc)),
        ),
    ]
