# Generated by Django 2.2.6 on 2019-10-22 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_auto_20191022_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 11, 47, 39, 910022, tzinfo=utc)),
        ),
    ]
