# Generated by Django 2.2.6 on 2019-10-22 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20191022_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 11, 48, 38, 158769, tzinfo=utc)),
        ),
    ]
