# Generated by Django 2.2.6 on 2019-10-29 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20191022_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 11, 34, 8, 991876, tzinfo=utc)),
        ),
    ]
