# Generated by Django 2.2.6 on 2020-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20191031_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='course',
            field=models.IntegerField(choices=[(0, '普通文章'), (1, 'Django+React全栈开发')], default=0),
        ),
    ]
