version: "3"
services:
  frontend:
    restart: always
    container_name: frontend
    build:
      context: ../../../frontend
      dockerfile: Dockerfile-dev
    command: "npm run dev"
    volumes:
      - ../../../frontend:/usr/src/frontend
    depends_on:
      - backend
      - nginx
    network_mode: "host"
  backend:
    restart: always
    container_name: backend
    build:
      context: ../../../backend
      dockerfile: Dockerfile-dev
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../../../backend:/code
    network_mode: "host"
  nginx:
    restart: always
    container_name: proxy
    image: nginx:latest
    volumes:
      - ../../nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    network_mode: "host"
