#+title: 近期关于哲学的一些感想
#+tags: 哲学
#+series: 随笔
#+created_at: 2021-03-20T08:58:06.125694+00:00
#+published_at: 2021-03-20T08:58:06.125694+00:00
#+summary: 这篇文章探讨了哲学的本质及其与现实生活的关系。作者认为，哲学是对人生的系统性反思，并不是远离现实生活的空谈。哲学家对名、实关系、矛盾双方相互转化的思考，都反映了他们对现实世界的深刻洞察。虽然哲学本身并不创造任何东西，但它能给我们一种看待世界的新视角，帮助我们换一种角度思考，从而在现实生活中获得积极有用的启示。

一直以来我都非常感兴趣，哲学这门学科在研究什么呢？因为平时常常会听到哲学被贴上​/远离世俗/​、​/空谈/​、​/无用/​等标签，我想会不会像计算机科学常被误解为修电脑的一样，是一种不了解带来的偏见？带着一些疑问，我阅读了一些相关书籍，顺带记录下一些思考，当然我仍然是个门外汉，水平有限，不值一哂。

* 哲学脱离现实吗？
冯友兰在《中国哲学简史》中说：”哲学是对人生的系统的反思“，当然这只是众多解释的一种，反思人生，并不是个容易的事情，系统性的反思，那就更加难了。不过如果说是对​*人生*​的反思，那又怎么会远离生活，脱离现实呢？

公孙龙子是战国时期名家的代表人物，他有个很出名的​*白马非马*​之辩，不管什么颜色的马，都是一种马，这是我们的常识，公孙龙却说：”马者。所以命形也；白者，所以命色也。命色者非命形也。故曰：白马非马。“，换句话说，公孙龙是在强调”马“、”白“与”白马“的内涵不同，用古希腊的哲学语言来说，公孙龙在强调”共相“间的区别。

同时公孙龙也是名家**”离坚白“**学派的代表，离坚白之辩大致是说，假如有块坚硬的白色石头，用眼看，只是白石，用手摸，就只是坚石，坚与白两种共相彼此分离。

举了名家的例子，名家恰好旨在​*欲推是辩，以正名实而化天下*​，可以发现，表面上名家在诡辩，让人感觉很荒诞，但这也反映出名家对名、实关系的反思，这与直觉、常识有些不符，我觉得正因为由反思带来的与直觉的不相符，使人感觉哲学，离现实很远。另外，这也引出另一个问题，不仅仅是名家，也许由于时代背景的原因，春秋战国时期诸子百家，都在研究一种形而上与治世的结合。

* 反者道之动
柏拉图认为在理想国中，应当​*哲学家为王*​，与其差不多同时代的中国的诸子百家虽然有各种不同的观念，但也几乎有一个共同的观点，即​*内圣外王*​。但是有些区别的地方在于，柏拉图认为哲学家统治理想国，是”被迫“，违背本心的，而中国的内圣外王，内圣是内在修养，人皆可以为尧舜，而人成了圣，他不仅适合为王，并且他积极为王，积极引导他人，出世与入世在这里相统一了起来。

在道家著作《道德经》中，常常能看到诸如**”大音希声，大象无形“​*、*​”有无相生，难易相成，长短相形“​*这样将一组对立的概念放在一起的句子，我认为它们可以概括为*​”反者道之动“​*，矛盾的双方，在一定条件下会向着相反方向转化。这么看来，古代哲人在追求超道德，追求与”天“、”道“的合一，这是*​出世**，而圣人治天下，又成了​*入世*​，恰恰符合”反者道之动“。

* 哲学”有用“吗？
知乎上有句流传很广的话，叫”先问是不是，再问问什么“，而”哲学有用吗？“这个问题，那首先也得想清楚什么是有用，什么是无用。我们在逛商场的时候，看到一件商品，也会想到这件东西买回去有没有用，这里的用，是指在日常生活上的价值，那以这个有用论，哲学有没有用呢？

《庄子》的人间世篇记载了一个故事，庄子与弟子遇到一棵大树，弟子问这样的大树怎么无人砍伐，庄子说这是不材之木，无所可用，所以能留存下来。好木材能打造家具，对人来说，是有用，对树来说，却是无用，因为会遭砍伐，反过来，对人无用的树，却不会被砍，这就是庄子说的​*无用之用*​。这里有用与无用的转换，只是换个角度看问题。

前面提到哲学是对人生系统性的反思，反思，当然不会是重新思一遍，而是要​*换一种思路，从另一个角度*​再次思考。关于庄子，还有一个故事，就是庄子的妻子去世，庄子却​/鼓盆而歌/​，说：

#+begin_quote
“不然。是其始死也，我独何能无概然！察其始而本无生，非徒无生也而本无形，非徒无形也而本无气。杂乎芒芴之间，变而有气，气变而有形，形变而有生，今又变而之死，是相与为春秋冬夏四时行也。人且偃然寝于巨室，而我噭噭然随而哭之，自以为不通乎命，故止也”
#+end_quote

庄子认为，有无，生死，成毁，如同圆上相对的点，而道则在圆心，圣人应与道合一，从道的角度看，不论生，也不论死，忘年忘义，振于无竟。常有人说道家的政治理论是愚民，使民无知，其实不然，有个词叫​*坐忘*​，道家的最终追求是​*不知*​，人生而​*无知*​，学而​*有知*​，忘而​*不知*​。就像金庸小说里，张无忌学太极拳，令狐冲学独孤九剑，招式繁复，变化多端，学完却要尽数忘却，要无招胜有招。

所以我想，哲学并不创造什么东西，就生产创造而言无用，但在现实生活中，它让我们换一种角度思考，就像庄子，亲人去世，固然痛苦，但在“道”的眼里，就如同四时变换一般，是形态的转移，无所谓生，也无所谓死。这是哲学对现实生活积极有用的方面。

#+begin_quote
哲学不报告任何事实，所以不能用具体的、物理的方法解决任何问题。例如，它既不能使人长生不死，也不能使人致富不穷。可是它能够给人一种观点，从这种观点可以看出生死相同，得失相等。从实用的观点看，哲学是无用的。哲学能给我们一种观点，而观点可能很有用。用《庄子》的话说，这是“无用之用”（《人间世》）。
#+end_quote
