# Generated by Django 3.0.5 on 2020-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.CharField(choices=[('编程', '编程'), ('网络安全', '网络安全'), ('杂谈', '杂谈')], default='编程', max_length=10),
        ),
    ]
