# Generated by Django 3.0.5 on 2020-07-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200701_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.Column'),
        ),
    ]
